# Generated by Django 4.2.7 on 2023-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_poster_alter_post_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата и время'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
